### ISSUE TITLE
USER STORY: Profile update

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#10]
# Description
**As a** User, **I want** to be able to update my profile information, **So that** my profile is up-to-date.

## Acceptance Criteria
1. The user should have access to a profile settings page to update their information.
2. On the profile settings page, there should be input fields or options to update the user's name, email address, and profile picture.
3. The user should be able to save their changes after updating their profile information.
4. Changes to the user's profile information should be reflected immediately throughout the website.
5. If the user changes their email address, they should receive a confirmation email to verify the change.

## Tasks
- [x] Create a profile settings page UI with input fields for name, email address, profile picture and favourite typ of climbing.
- [x] Implement backend functionality to handle profile information updates.
- [x] Design the page Layout.
- [x] Test the profile information update process to ensure accuracy and user satisfaction.
