### ISSUE TITLE
USER STORY: View my comments

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#11]
# Description
**As a** User, **I want** to be able to see the climbing gyms i have made a comment on, **So that** I can access/see them quickly and easy.

## Acceptance Criteria
1. The user should have a "My comments" section or tab in their profile page.
2. The "My comments" section should display a list of climbing gyms that the user has commented on rated.
3. Each climbing gym in the "My comments" section should include basic information such as the name/title, the rating and the comments.
4. The user should be able to click on a climbing gym to view its full details of the gym.
5. If the user has not made any comments, the "My Comments" section should display a message indicating that there are no comments have been made.

## Tasks
- [x] Add a "My Comments" section or tab to the user's profile page UI.
- [x] Implement backend functionality to fetch and display the user's comments.
- [x] Design the layout for displaying climbing gyms information within the "My comments" section.
- [x] Ensure that clicking on a comments/climbing gym redirects the user to the climbing gym detailed view.
- [x] Handle cases where the user has no made a comment on a climbing gym. 
- [x] Test the "My comments" section to ensure it accurately displays the user's comments and provides a smooth user experience.
