### ISSUE TITLE
USER STORY: Make a comment

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#14]
# Description
**As a** User, **I want** to be able a review climbing gyms I have been at by leaving a comment, **So that** our user's can make a informed decision.

## Acceptance Criteria
1. Users should have the option to leave a comment or review after trying a climbing gym from the climbing gym details page.
2. Comments left by users should be displayed below the climbing gym details, showing the user's name, timestamp, rating and comment text(the text is optional)
3. Comments/reviews should be presented in a clear and organised way. The comments should be easy to read and navigate through.

## Tasks
- [x] Add a comment section to the climbing gym details page UI.
- [x] Implement backend functionality to handle user comments for the climbing gym.
- [x] Design the layout for displaying user comments and reviews, including user names, timestamps, and comment text.
- [x] Implement functionality to submit.
- [x] Test the comment and review functionalities to ensure usability and reliability.
