### ISSUE TITLE
USER STORY: Make a Rating

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#15]
# Description
**As a** User, **I want** to be able to rate a climbing gym that I have tried, **So that** other users can make an informed decision about which climbing gym to try. 

## Acceptance Criteria
1. Users should have the option to rate a climbing gym after trying them from the climbing gym details page.
3. The rating system should use a scale (e.g., stars) to allow users to indicate their satisfaction with the climbing gym.

## Tasks
- [x] Add a rating system (e.g., stars) to the climbing gym details page UI.
- [x]  Implement backend functionality to handle user ratings for climbing gym.
- [x]  Test the rating functionalities to ensure accuracy and reliability.
