### ISSUE TITLE
USER STORY: View Climbing gym page

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#19]
# Description
**As a** User, **I want** to be able to see detail information about the climbing gym, **So that** I can easily see where the gym is located, the climbing gyms social media and other details.

## Acceptance Criteria
1. Each climbing gym should there own page that display the information about the climbing gyms such as the gyms name, image, and a brief description.
2. Users should be able to click on the "website" and be connected to the climbing gyms webstie.
3. The detailed view of a climbing gym should include About, images, adress, map, rating, and any other relevant details.
4. Users should have the option to comment on the climbing gym.

## Tasks
- [x] Create a dedicated page climbing gyms.
- [x] Design the layout for displaying multiple climbing gyms, including titles, images, and descriptions.
- [x] Implement functionality to fetch and display climbing gyms from a database or external source.
- [x] Design the layout for the detailed view of a climbing gyms, including all relevant information..
