### ISSUE TITLE
USER STORY: Register user

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#2]
# Description
**As a** User ,**I want** to be able to register a profile, **So that** I can login and access the website's features

## Acceptance Criteria
1. The user should be able to navigate to the sign-up page from the home page
2. The sign-up page should contain input fields for the user's email adress, password, bio and favorite climb
3. The user should receive a confirmation message upon successful sign-up.

## Tasks
- [x] Implement the sign-up page UI.
- [x] Set up the backend to handle user registration.
- [ ] (Validate user input for email address and password.)
- [ ] Show a confirmation message to the user upon successful registration.
- [x] Test the sign-up process to ensure functionality and user experience.
