### ISSUE TITLE
USER STORY: Create climbing gym

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#22]
# Description
**As a** Staff user, **I want** be able to create a climbing gym, **So that** my climbing gym can be featured on the website

## Acceptance Criteria
1. Staffs should have the option to create a climbing gym.
2. The staff should have access to create the climbing gym from their profile.
3. The create climbing gym page should contain input fields for the, about text, images ect
4. The staff should receive a confirmation message upon successful created climbing gym.

## Tasks
- [x] Implement the create climbing gym page UI.
- [x] Set up the backend to handle creating a climbing gym.
- [x] Show a confirmation message to the staff creating a climbing gym successfully.
- [x] Test the creating process to ensure functionality and user experience.
