### ISSUE TITLE
USER STORY: Edit Climbing gym

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#23]
# Description
**As a** staff user ,**I want** to be able to edit my created climbing gym, **So that** the information is updated

## Acceptance Criteria
1. The staff should have access to a climbing gym settings page to update their information.
2. On the climbing gym settings page, there should be input fields or options to update the name, about, pictures, social media ect.
3. The staff should be able to save their changes after updating the climbing gym information.
4. Changes to the climbing gym information should be reflected immediately throughout the website.

## Tasks
- [x] Create a climbing gym settings page UI with input fields for name, about, pictures, social media ect.
- [x] Implement backend functionality to handle profile information updates.
- [x] Design the page Layout.
- [x] Test the climbing gym information update process to ensure accuracy and user satisfaction.
