### ISSUE TITLE
USER STORY: View my climbing gyms

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#24]
# Description
**As a** Staff user, **I want** to be able to see the climbing gyms i have created, **So that** I can access/see them quickly and easy.

## Acceptance Criteria
1. The staff should have a "My climbing gyms" section or tab in their profile page.
2. The "My climbing gyms" section should display a list of climbing gyms that the staff has created.
3. Each gym in the "My climbing gym" section should include basic information such as the name/title, the about and rating.
4. The staff should be able to click on a climbing gym to view its full details of the gym.
5. If the staff has not created climbing gym, the "My climbing gyms" section should display a message indicating that they have not yet created a climbing gym.

## Tasks
- [x] Add a "My climbing gym" section or tab to the staff's profile page UI.
- [x] Implement backend functionality to fetch and display the staff's climbing gym.
- [x] Design the layout for displaying climbing gyms information within the "My climbing gym" section.
- [x] Ensure that clicking on a climbing gym redirects the staff to the climbing gym detailed view.
- [x] Handle cases where the staff has no created a climbing gym. 
- [x] Test the "My climbing gym" section to ensure it accurately displays the staff's climbing gym and provides a smooth user experience.
