### ISSUE TITLE
USER STORY: Delete climbing gym

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#25]
# Description
**As a** Staff, **I want** to be able to delete my climbing gym, **So that** I can correct mistakes, update information, or remove inappropriate content as needed.

##Acceptance Criteria
1. Staff's should have the option to delete their climbing gym from the their profile.
2. The delete options should be accessible only to the staff who originally created the climbing gym.
4. Clicking on the delete option should prompt the staff to confirm the deletion of their climbing gym.
5. The staff have to conform the deletion before the climbing gym it deleted. 
6. After deleting a climbing gym, the changes should be reflected immediately.
7. Staff's should receive confirmation after successfully deleting a climbing gym.
8. Staff's should receive a error message if they could not create a climbing gym

## Tasks
 - [x] Add delete options or buttons to each climbing gym's on the staffs profile page UI.
 - [x] Implement backend functionality to handle climbing gym deletion requests.
 - [x] Implement functionality to confirm the deletion of a climbing gym and remove it from the database.
 - [x] Test the deletion functionality to ensure accuracy and reliability.
 - [x]  Provide feedback to users upon successfully deleting a climbing gym to confirm that the action was completed successfully.
