### ISSUE TITLE
USER STORY: Delete profile

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#26]
# Description
**As a** User, **I want** to be able to delete my profile, **So that** I can remove the account if it is not needed anymore.

##Acceptance Criteria
1. Users should have the option to delete their account.
2. The delete options should be accessible only to the user who originally created the account.
4. Clicking on the delete option should prompt the user to confirm the deletion of their account.
5. The user have to conform the deletion before the account is deleted. 
6. After deleting a account, the changes should be reflected immediately.
7. User's should receive confirmation after successfully deleting a account.
8. User's should receive a error message if they could not delete the account.

## Tasks
 - [x] Add delete options or buttons on the user's profile page UI.
 - [x] Implement backend functionality to handle account deletion requests.
 - [x] Implement functionality to confirm the deletion of the account and remove it from the database.
 - [x] Test the deletion functionality to ensure accuracy and reliability.
 - [x] Provide feedback to users upon successfully deleting the account to confirm that the action was completed successfully.
