### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#27]
# Description
**As a** Staff ,**I want** to be able to register a profile, **So that** I can login and access the website's features and create climbing gyms

## Acceptance Criteria
1. The staff should be able to navigate to the sign-up page from the home page
2. The sign-up page should contain input fields for the staff user's email adress, password, bio and favorite climb
3. The staff user should receive a confirmation message upon successful sign-up.

## Tasks
- [ ] Implement the sign-up page UI.
- [ ] Set up the backend to handle user registration.
- [ ] (Validate user input for email address and password.)
- [ ] Show a confirmation message to the user upon successful registration.
- [ ] Test the sign-up process to ensure functionality and user experience.
