### ISSUE TITLE
USER STORY: View comments

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#29]
# Description
**As a** User, **I want** to be able to see the reviews from other users, **So that** I can make a I can make an informed decision about which climbing gym to try.

## Acceptance Criteria
1. Comments left by users should be displayed below the climbing gym details, showing the user's name, timestamp, rating and comment text (optional).
2. Users should be able to see all comments and reviews from other users on the climbing gym details page.
3. The comment section should be interactive, allowing users to like comments .
4. Comments and reviews should be presented in a clear and organised way. The comments should be easy to read and navigate through.

## Tasks
- [x] Add a comment section to the climbing gym details page UI.
- [x] Implement backend functionality to handle user comments and reviews for the climbing gym.
- [x] Design the layout for displaying user comments and reviews, including user names, timestamps, and comment text.
- [x] Implement functionality to display, and manage user comments.
- [x] Test the comment and review functionalities to ensure usability and reliability.
