### ISSUE TITLE
USER STORY: View profile

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#30]
# Description
**As a** user ,**I want** be able to see my profile and the information that is displayed, **So that** i can see if i need/what to edit any information

## Acceptance Criteria
1. The User have own page that display the information about themself such as the username, email address, profile picture and favourite typ of climbing.
2. The detailed view of a users profile should be displayed so it's easy to read and navigate through.
3. The user should be able to view buttons to edit or delete on the profile.

## Tasks
- [x] Create a profile page for the user.
- [x] Design the layout for displaying user profiles, including the username, email address, profile picture and favourite typ of climbing.
- [x] Implement functionality to the user profile from a database.
- [x] Design the layout for the detailed view of a user profile, including all relevant information.
