### ISSUE TITLE
USER STORY: View climbing tips

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#34]
# Description
**As a** logged in User  ,**I want** be able to see climbing tips, **So that** I can read about tips about climbing 

## Acceptance Criteria
1. The website should have a dedicated page or section for browsing tips about climbing or training tips.
3. Users that are logged in should be able to click on a tips to view its detailed information.
4. The detailed view of a tips should include a small introduction, the main text and when is was posted 
5. Users should have the option to like a post/tips.
6. The browsing experience should be user-friendly and intuitive, allowing users to easily navigate between different tips.

## Tasks
- [ ] Create a dedicated page or section for browsing tips.
- [ ] Design the layout for displaying multiple tips, including titles, images, and introduction. 
- [ ] Implement functionality to fetch and display tips from a database.
- [ ] Design the layout for the detailed view of a tips, including all relevant information.
- [ ] Implement functionality to like a tip. 
- [ ] Test the tips browsing and detailed view functionalities to ensure they meet user expectations and provide a seamless experience.
