### ISSUE TITLE
USER STORY: Like a tip for climbing

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#35]
# Description
**As a** in logged User,**I want** be able to to like a tip, **So that** i can find is on my profile and find it easy

##Acceptance Criteria
1. Users that are inloggad should have the option to like a climbing tip the climbing tip details page.
2. The number of likes should be shown on the climbing tip details page.
3. The number of likes be presented in a clear and organised way.

##Tasks
 - [ ] Add a like section to the climbing tip details page UI.
 - [ ] Implement backend functionality to handle user like for the climbing tip.
 - [ ] Design the layout for displaying number of likes.
 - [ ] Implement functionality to like a climbing tip.
 - [ ] Test the like functionalities to ensure usability and reliability.
