### ISSUE TITLE
USER STORY: View my like climbing tips

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#36]
# Description
**As a** logged in User, **I want** to be able to see the climbing tips i have likes, **So that** I find them easily and read them again.

## Acceptance Criteria
1. The user should have a "My liked climbing tips" section or tab in their profile page.
2. The "My liked climbing tips" section should display a list of the climbing tips that the user has liked.
3. Each climbing tip in the "My liked climbing tips" section should include basic information such as the title, the beginning of the introduction.
4. The user should be able to click on a climbing tip to view its full details of the tip.
5. If the user has not made any comments, the "My liked climbing tips" section should display a message indicating that there are no likes have been made.

## Tasks
- [ ] Add a "My liked climbing tips" section or tab to the user's profile page UI.
- [ ] Implement backend functionality to fetch and display the user's likes.
- [ ] Design the layout for displaying climbing tips information within the "My liked climbing tips" section.
- [ ] Ensure that clicking on a tips/climbing tip redirects the user to the climbing tips detailed view.
- [ ] Handle cases where the user has no made any likes on a climbing tip. 
- [ ] Test the "My liked climbing tips" section to ensure it accurately displays the user's likes and provides a smooth user experience.
