### ISSUE TITLE
USER STORY: Contact us form

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#38]
# Description
**As a** User/Staff,**I want** to be able to send a message to the admin, **So that** i can become contact the admin if i have any questions, repost an issue or as a user like to uppdrag my profile to staff or repost an issue

## Acceptance Criteria
1. The user should be able to navigate to the login page from the home page.
2. The contact us page should contain input fields for the user's name, email, typ of question and message.
3. The user should receive an error message if the user enter the incorrect password och email.
4. If the contact is submitted successfully, the user should be redirected to the thanks you page.

## Tasks
- [ ]  Implement the contact us and thank you  page UI.
- [ ] Set up the backend to handle the form.
- [ ] Provide appropriate error messages for form is  invalid.
- [ ] Redirect the user to Thank you Page upon successful submission
- [ ] Test the contact from process to ensure functionality and security.
