### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by Ko11e** [Ko11e/Climb-that-wall#7]
# Description
**As a** User, **I want** to see a selection of featured climbing gyms on the home page, **So that** I can quickly discover new and popular climbing gyms

## Acceptance Criteria
1. On the home page, there should be a section dedicated to displaying climbing gyms.
2. The climbing gym section should showcase a visually appealing layout with images, titles, and brief descriptions.
3. Users should be able to click on a climbing gym Image to view the full details of the climbing gym.
4. Users should be able to click on a link "See all" and be directed to a search site for the climbing gyms.
5. The selection of featured climbing gyms should be dynamic and regularly updated based on popularity, user preferences, or other relevant criteria.

## Tasks
- [ ] ]Design a layout for the featured climbing gym section on the home page.
- [ ] Implement functionality to retrieve a selection of featured climbing gyms from the database.
- [ ] Display the retrieved climbing gym on the home page, including images, titles, and brief descriptions.
- [ ] Ensure that clicking on the "See all" redirects the user to a search page. 
- [ ] Ensure that clicking on a recipe card redirects the user to the climbing gym details page.
